# Configuration file

DETECTION_CONF: float = 0.25
NMS_TH: float = 0.45
GREEDY_NMM_TH = 0.4
SAHI_MATCHING_METRIC: str = 'IOS'

USE_TTA = False
INPUT_SIZE = 640
WINDOW_SIZE = -1
WINDOW_STRIDE = 3 * WINDOW_SIZE // 4
BATCH_SIZE = 1
